# Generated by Django 4.2.7 on 2023-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
