# Generated by Django 4.2.7 on 2023-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0002_alter_movies_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
