# Generated by Django 4.2.8 on 2023-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to='ex.user'),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to='ex.user'),
        ),
    ]
