# Generated by Django 4.2.8 on 2023-12-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_customuser_nb_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': (('downvote_tip', 'can downvote a tip'),)},
        ),
    ]
